version: '3'
services:
  web:
    build: .
    container_name: rspec_rails
    command: rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    links:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - rspec_rails:/var/lib/postgresql/data
volumes:
  rspec_rails: